---
- hosts: localhost
  tasks:
    - name: Stop VM
      proxmox_kvm:
        api_user: nikandafee@pve
        api_password: azbgsm4m3s
        api_host: 10.147.248.21
        vmid: 158
        state: stopped

